### ISSUE TITLE
Copy URL broken & Android share dialog

### ISSUE THREAD

**Issue by jmfayard** [thepracticaldev/DEV-Android#58]
Hello,
Copy pasting a link to a dev.to article works for me in chrome but do not work inside the dev.to Android app

**Comment by VarunBarad** [comment]
Can you please explain a bit more?
Where does the pasting not work? When writing/editing an article/comment? If not there then where?

Can you give steps to reproduce the problems?

**Comment by jmfayard** [comment]
@VarunBarad 
clicking on the URL in this screen copy the URL when I open an article in Chrome, but not when I do it inside the Android app

![photo_2019-10-21 16 17 47](https://user-images.githubusercontent.com/459464/67213456-56903b80-f41e-11e9-930b-b4af335a1b77.jpeg)

**Comment by VarunBarad** [comment]
@jmfayard I just tried it both in the app and in chrome and it didn't work at any of those places 😅

**Comment by jmfayard** [comment]
You are right. It used to work though so that's probably a recent regression.

Suggestions:
- fix the website itself
- in the Android app, I feel that this feature should be overridden and that the native Android share dialog should be used instead. It includes a copy URL feature

**Comment by VarunBarad** [comment]
You are right. The website needs to be fixed because it is expected that the copy URL functionality should work in Chrome atleast.

Regarding the Android app. We would need to implement two separate things from what you are saying. Because the "Share" functionality shares the title of the article along with its URL. So when a user decides to share for example [this article](https://dev.to/ben/my-new-home-office-setup-2lfd) from the platform then what is copied on their clipboard is

> My new home office setup https://dev.to/ben/my-new-home-office-setup-2lfd

So we need to keep the copy-url thing being displayed as is, but behind the scenes we invoke the native platform's "copy to clipboard" code.

And the share dialog needs to be implemented separately.

PS: I am almost done with the native code for "copy to clipboard" so will be sending a pull request in a few minutes.

**Comment by jmfayard** [comment]
@VarunBarad ah yes, Android is annoying about this. 
There is a work-around for this:
https://cketti.de/2016/06/15/share-url-to-clipboard/
